# Author: Mengty LIM
---
all:
  children:
    dev:
      children:
        app_servers:
          hosts:
            dev-app-a01.dev.bank.internal:
              ansible_host: 10.10.32.200
        k8s_control_plane:
          hosts:
            dev-k8s-cp-a01.dev.bank.internal:
              ansible_host: 10.10.32.10
              rke2_bootstrap: true
        k8s_workers:
          children:
            k8s_workers_general:
              hosts:
                dev-k8s-general-a01.dev.bank.internal:
                  ansible_host: 10.10.32.40
                dev-k8s-general-a02.dev.bank.internal:
                  ansible_host: 10.10.32.41

    linux:
      children:
        app_servers: {}
        k8s_control_plane: {}
        k8s_workers: {}
